use dbFP;
create table users(
    id int NOT NULL PRIMARY KEY AUTO_INCREMENT,
    pw varchar (200) NOT NULL,
    email varchar (200) NOT NULL,
    username varchar (200) not null,
    foto varchar(2000) not null default 'assets/img/cover/profile/ojan.jpg',
    CONSTRAINT UC_user UNIQUE (id,username,email),
    INDEX(pw,email)
);
create table video(
    id int NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(200) NOT NULL,
    descr VARCHAR(2000) NOT NULL,
    rate float NOT NULL,
    watch int not null,
    path varchar(1000) not null,
    CoverLandscape varchar(1000),
    CoverPotrait varchar(1000),
    upload datetime default now(),
    INDEX(name)
);

create table genre(
    movieID int not null,
    genre varchar(1000) not null,
    FOREIGN KEY (movieID) REFERENCES video(id)
);
create table favorite(
    users int not null,
    movieID int NOT NULL,
    FOREIGN KEY (users) REFERENCES users(id),
    FOREIGN KEY (movieID) REFERENCES video(id)
);

create table watchlist(
    users int not null,
    movieID int NOT NULL,
    FOREIGN KEY (users) REFERENCES users(id),
    FOREIGN KEY (movieID) REFERENCES video(id)
);

create table recent(
    users int not null,
    movieID int NOT NULL,
    lastTime datetime default now(),
    FOREIGN KEY (users) REFERENCES users(id),
    FOREIGN KEY (movieID) REFERENCES video(id)
);

create table theAdmin(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username varchar(10),
    pw VARCHAR (10)
);

insert into video(name,descr,rate,path,coverlandscape,coverpotrait) VALUES
('Kimi No Nawa',
'Menceritakan kedua anak SMA bernama Mitsuha dan Taki yang tidak mengenal satu sama lainnya. Tapi suatu malam, mereka tiba-tiba bertukar tempat. Mitsuha terbangun di tubuh Taki, dan dia di dalam tubuhnya. Kejadian aneh ini terus terjadi secara acak, dan keduanya harus menyesuaikan hidup mereka di sekitar satu sama lain.',
9.12,
'assets/movie/kiminonawa.mkv',
'assets/img/cover/kiminonawaland.jpg',
'assets/img/cover/kiminonawapotr.jpg'),
('Tenki no Ko',
'Tokyo selalu dilanda hujan yang terus menerus turun tanpa henti. Di tengah hujan yang terlihat abadi ini, ada seorang anak SMA yang kabur dari rumah, Morishima Hodaka. Untuk memenuhi biaya hidup, dia berakhir bekerja di sebuah kantor penerbit kecil. Di saat yang sama, ada anak yatim piatu bernama Amano Hina yang juga berupaya untuk bekerja demi memenuhi kebutuhan hidupnya bersama adiknya.Nasib keduanya terjalin ketika Hodaka berusaha menyelamatkan Hina dan memutuskan untuk melarikan diri bersama. Selanjutnya, Hodaka mengetahui bahwa Hina memiliki kekuatan aneh yang mengejutkan, yaitu kemampuan untuk mencerahkan hari dengan cara berdoa. Karena cuaca di Tokyo sangat tak menentu, Hodaka melihat potensi kemampuan ini. Dia meminta Hina untuk menjadi gadis cerah, seorang gadis yang akan mencerahkan hari untuk orang-orang yang membutuhkannya. Hal itu menjadi keseharian mereka. Namun, kekuatan yang besar selalu memiliki harga yang mahal.',
8.3,
'assets/movie/tenkinoko.mkv',
'assets/img/cover/tenkinokoland.jpg',
'assets/img/cover/tenkinokopotr.jpg'),
('Anohana',
'Menceritakan kisah sekelompok enam anak. Hingga suatu hari, salah satu dari mereka (Menma) meninggal karena kecelakaan. Sepuluh tahun kemudian, Menma yang menjadi arwah hanya bisa dilihat oleh Jinta.Sejak kematian Menma, Jinta menjadi depresi dan mantan teman-temannya telah berpisah, sementara masih dipersatukan oleh ingatan yang menghantui kehilangan teman lama mereka, Menma. Melalui cerita yang berliku-liku, kita belajar untuk benar-benar merasakan karakter-karakter ini dan bahkan melihat sedikit dari mereka dalam diri kita sendiri.',
8.59,
'assets/movie/anohana.mkv',
'assets/img/cover/anohanaland.jpg',
'assets/img/cover/anohanapotr.jpg'),
('Gintama',
'Bercerita tentang kehidupan sehari-hari tokoh utamanya, yaitu Sakata Gintoki, yang mendirikan usaha bernama “Yorozuya” bersama dua temannya dan satu anjing. Mereka bersedia mengerjakan tugas apa saja asalkan dibayar agar dapat membiayai kehidupan sehari-hari.',
8.84,
'assets/movie/gintama.mkv',
'assets/img/cover/gintamaland.jpg',
'assets/img/cover/gintamapotr.jpg'),
('Spirited Away',
'Spirited Away mengisahkan petualangan magis gadis 10 tahun bernama Chihiro. Perjalanan dimulai ketika ia terpaksa mengikuti ayah dan ibunya untuk pindah domisili ke wilayah baru.',
8.81,
'assets/movie/spiritedaway.mkv',
'assets/img/cover/spiritedawayland.jpg',
'assets/img/cover/spiritedawaypotr.jpg'),
('Violet Evergarden',
'Menceritakan tentang Violet, seorang yang bertugas untuk menulis dan menyampaikan surat dari kliennya kepada orang terkasih. Karena pekerjaannya itu, Violet harus menemui klien dan memahami perasaan mereka.',
8.88,
'assets/movie/violet.mkv',
'assets/img/cover/violetland.jpg',
'assets/img/cover/violetpotr.jpg'),
('Fate Heaven Feel 3',
'Suatu hari setelah membersihkan Dojo Panahan di sekolahnya, ia melihat sekilas pertarungan antara makhluk super yang terlibat dalam Perang Cawan Suci. Perang Cawan Suci merupakan sebuah pertempuran di mana tujuh orang penyihir yang disebut Master beserta para Servant-nya bertarung dengan sengit untuk memperebutkan Cawan Suci. ',
9.12,
'assets/movie/fatehf.mkv',
'assets/img/cover/fatehfland.jpg',
'assets/img/cover/fatehfpotr.jpg'),
('Josee to Tora to Sakana-tachi',
'Tsuneo seorang mahasiswa yang bekerja part time di toko alat selam tiba-tiba menjadi pengasuh seorang wanita muda yang menggunakan kursi roda. Keputusan tersebut terpaksa ia ambil karena harus menabung demi menggapai impiannya melanjutkan studi ke Meksiko.',
8.66,
'assets/movie/josee.mkv',
'assets/img/cover/joseeland.jpg',
'assets/img/cover/joseepotr.jpg'),
('Kimetsu no Yaiba Mugen Ressha-hen',
'Bersama adiknya, Nezuko, serta Zenitsu dan Inosuke, Tanjiro bergabung dengan Flame Hashira Kyojuro Rengoku, salah satu pendekar pedang terkuat di Demon Slayer Corps.',
8.38,
'assets/movie/kny.mkv',
'assets/img/cover/knyland.jpg',
'assets/img/cover/knypotr.jpg'),
('Saekano Fine',
'Bercerita tentang kehidupan Tomoyo Aki, otaku yang merupakan anak SMA yang bekerja paruh waktu demi mengumpulkan BD miliknya. Dengan keberuntungan yang sangat baik, dia bertemu dengan Megumi Kato, gadis tercantik yang pernah ditemuinya. Tentu, pertemuannya yang berliku membuat hubungannya rumit. Eriri Spencer Sawamura, teman masa kecilnya yang blasteran yang selalu menghargai hubungannya dengan tokoh utama. Kasumigaoka Utaha, orang yang dingin, terkenal jenius dalam sastra yang menyingkirkan orang-orang dari si tokoh utama.',
8.42,
'assets/movie/saekano.mkv',
'assets/img/cover/saekanoland.jpg',
'assets/img/cover/saekanopotr.jpg'),
('Hello World',
'Bercerita soal time traveling alias penjelajah waktu dan dunia di masa lampau besutan sutradara Tomohiko Ito dan diproduksi oleh Graphinica ini dirilis pada tanggal 20 September 2019.',
7.84,
'assets/movie/helloworld.mkv',
'assets/img/cover/helloworldland.jpg',
'assets/img/cover/helloworldpotr.jpg'),
('Konosuba 3',
'Mengisahkan seorang otaku sekaligus hikkikomori bernama Kazuma Satou. Sehari-hari Kazuma menghabiskan harinya hanya berada di dalam kamarnya sambil bermain game. Suatu hari ia harus berhadapan dengan dunia luar, hanya demi membeli sebuah game yang baru di rilis. Sepulang dari perjalanan membeli game tersebut, ia bertemu dengan seorang gadis yang tengah menyebrang jalan. Namun tiba-tiba, ia melihat siluet kendaraan besar yang akan menabrak gadis tersebut. Meski penuh keraguan, ia akhirnya memberanikan diri untuk mendorong gadis tersebut. Sang gadis bisa selamat, tetapi Kazuma justru malah meninggal akibat perbuatannya.',
8.56,
'assets/movie/konosuba.mkv',
'assets/img/cover/konosubaland.jpg',
'assets/img/cover/konosubapotr.jpg'),
('Youjou Senki',
'Youjo Senki Saga of Tanya the Evil bertempat di sebuah dunia yang dilanda perang yang tak berkesudahan, terdapat sebuah negeri kekaisaran yang memiliki kekuatan industri serta militer yang sangat unggul. Kekaisaran tersebut memiliki armada militer dan penyihir yang sangat handal dan jumlah besar',
8.26,
'assets/movie/youjosenki.mkv',
'assets/img/cover/youjosenkiland.jpg',
'assets/img/cover/youjosenkipotr.jpg'),
('SAO Ordinal Scale',
'Sword Art Online bercerita mengenai sebuah game online canggih di masa depan, di mana para pemainnya harus mengenakan sebuah helm bernama NerveGear. Helm tersebut diceritakan bisa menstimulasi otak penggunanya, sehingga mereka bisa masuk dan merasakan langsung bagaimana dunia virtual dari game yang mereka mainkan.',
8.23,
'assets/movie/sao.mkv',
'assets/img/cover/saoland.jpg',
'assets/img/cover/saopotr.jpg'),
('Fate GO Camelot',
'Ksatria pengembara, Bedivere, mencapai akhir perjalanannya. Saat itu tahun 1273 M. di Yerusalem. Tanah Suci telah diubah menjadi padang pasir yang luas, orang-orang telah dipaksa keluar dari rumah mereka, dan tiga kekuatan besar saling berperang di gurun ini. Dengan seluruh kerajaannya dipanggil ke negeri asing, Ozymandias, Raja Matahari, diam-diam berkomplot melawan tirani dunia aneh ini. Orang-orang gunung, pelindung mereka yang dirampas dari tanah mereka, menunggu kesempatan untuk memberontak.',
6.80,
'assets/movie/fgocam.mkv',
'assets/img/cover/fgocamland.jpg',
'assets/img/cover/fgocampotr.jpg'),
('Aobuta Movie',
'Film ini diadaptasi dari novel volume keenam dan ketujuh Seishun Buta Yarou wa Yumemiru Shoujo no Yume wo Minai dan Seishun Buta Yarou wa Hatsukoi Shoujo no Yume wo Minai. Proyek film ini tak hanya fokus pada karakter utama Sakuta Azusagawa dan Mai Sakurajima, tetapi juga pada seorang gadis misterius bernama Shouko Makinohara. Anime ini akan menceritakan perasaan dan keinginan masing-masing karakter yang saling bersinggungan.',
8.8,
'assets/movie/aobuta.mkv',
'assets/img/cover/aobutaland.jpg',
'assets/img/cover/aobutapotr.jpg'),
('Chuunibyou Take On Me',
'Film ini akan menampilkan cerita baru di mana Yuuta dan Rikka berada di tahun ketiga sekolah menengah mereka. Suatu hari di musim semi, Touka mengatakan bahwa dia akan membawa Rikka ke Italia bersamanya, karena urusan pekerjaannya, dan dia tidak ingin meninggalkan Rikka sendirian. Touka juga khawatir kalau Rikka tidak cukup kompeten untuk meyakinkan T. Geng-geng dari klub menyarankan Yuuta, yang tidak ingin dipisahkan, untuk kawin lari dengan Rikka !! Drama pelarian di seluruh Jepang dimulai.',
8.03,
'assets/movie/chuunibyou.mkv',
'assets/img/cover/chuunibyouland.jpg',
'assets/img/cover/chuunibyoupotr.jpg'),
('Koe no Katachi',
'Ishida Shouya adalah anak laki-laki yang ceria dan sering membuat masalah. Suatu hari, datang murid baru yang pindah ke kelasnya. Dia adalah Nishimiya Shouko, seorang gadis penyandang tunarungu. Pertemuan Ishida dengan gadis itu menjadi awal perubahan besar dalam kehidupan dan kepribadiannya.',
8.98,
'assets/movie/koenokatachi.mkv',
'assets/img/cover/koenokatachiland.jpg',
'assets/img/cover/koenokatachipotr.jpg'),
('No Game No Life Zero',
'Sebelum kedatangan Sora dan Shiro, terjadilah sebuah perang besar yang mengoyak daratan, mendobrak langit, menghancurkan bintang, dan membahayakan umat manusia. Dalam keadaan yang memprihatinkan itu, salah satu manusia yang bernama Riku, membimbing umat manusia untuk melewati hari esok. Suatu hari, ketika Riku menjelajahi reruntuhan kota Elf, dia bertemu dengan Ex-machina bernama Shuvi. Shuvi merupakan unit pengumpul data yang sedang melakukan investigasi mengenai hati manusia. Sampai ia memahami apa yang disebut hati manusia, Shuvi memutuskan untuk berada di sisi Riku.',
8.58,
'assets/movie/nogamenolife.mkv',
'assets/img/cover/nogamenolifeland.jpg',
'assets/img/cover/nogamenolifepotr.jpg');

insert into genre VALUES
(1,'Drama'),
(1,'Romance'),
(1,'School'),
(1,'Supernatural'),
(2,'Drama'),
(2,'Fantasy'),
(2,'Romance'),
(2,'Sliceoflife'),
(3,'Sliceoflife'),
(3,'Drama'),
(3,'Supernatural'),
(3,'Action'),
(4,'Comedy'),
(4,'Drama'),
(4,'Parody'),
(4,'Samurai'),
(4,'Sci-Fi'),
(4,'Shounen'),
(5,'Adventure'),
(5,'Drama'),
(5,'Supernatural'),
(6,'Drama'),
(6,'Fantasy'),
(6,'Sliceoflife'),
(6,'Romance'),
(7,'Action'),
(7,'Fantasy'),
(7,'Magic'),
(7,'Supernatural'),
(8,'Drama'),
(8,'Romance'),
(8,'Sliceoflife'),
(9,'Demons'),
(9,'Historical'),
(9,'Shounen'),
(9,'Supernatural'),
(10,'Comedy'),
(10,'Ecchi'),
(10,'Harem'),
(10,'Romance'),
(10,'School'),
(11,'Sci-Fi'),
(11,'Romance'),
(12,'Adventure'),
(12,'Comedy'),
(12,'Fantasy'),
(12,'Magic'),
(12,'Isekai'),
(13,'Isekai'),
(13,'Action'),
(13,'Magic'),
(13,'Military'),
(14,'Action'),
(14,'Adventure'),
(14,'Fantasy'),
(14,'Game'),
(14,'Romance'),
(15,'Action'),
(15,'Fantasy'),
(15,'Magic'),
(15,'Supernatural'),
(16,'Comedy'),
(16,'Romance'),
(16,'School'),
(17,'School'),
(17,'Comedy'),
(17,'Drama'),
(17,'Romance'),
(17,'Sliceoflife'),
(18,'Drama'),
(18,'School'),
(18,'Romance'),
(19,'Comedy'),
(19,'Ecchi'),
(19,'Fantasy'),
(19,'Game'),
(19,'Supernatural')
